/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CustomerImport } from './routes/_customer'
import { Route as AgentImport } from './routes/_agent'
import { Route as IndexImport } from './routes/index'
import { Route as CustomerDashboardImport } from './routes/_customer/dashboard'
import { Route as CustomerTransactionsAddImport } from './routes/_customer/transactions/add'
import { Route as AgentAgentDashboardImport } from './routes/_agent/agent/dashboard'
import { Route as AgentAgentCustomersAddImport } from './routes/_agent/agent/customers/add'
import { Route as AgentAgentAccountsAddImport } from './routes/_agent/agent/accounts/add'

// Create/Update Routes

const CustomerRoute = CustomerImport.update({
  id: '/_customer',
  getParentRoute: () => rootRoute,
} as any)

const AgentRoute = AgentImport.update({
  id: '/_agent',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CustomerDashboardRoute = CustomerDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => CustomerRoute,
} as any)

const CustomerTransactionsAddRoute = CustomerTransactionsAddImport.update({
  path: '/transactions/add',
  getParentRoute: () => CustomerRoute,
} as any)

const AgentAgentDashboardRoute = AgentAgentDashboardImport.update({
  path: '/agent/dashboard',
  getParentRoute: () => AgentRoute,
} as any)

const AgentAgentCustomersAddRoute = AgentAgentCustomersAddImport.update({
  path: '/agent/customers/add',
  getParentRoute: () => AgentRoute,
} as any)

const AgentAgentAccountsAddRoute = AgentAgentAccountsAddImport.update({
  path: '/agent/accounts/add',
  getParentRoute: () => AgentRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_agent': {
      preLoaderRoute: typeof AgentImport
      parentRoute: typeof rootRoute
    }
    '/_customer': {
      preLoaderRoute: typeof CustomerImport
      parentRoute: typeof rootRoute
    }
    '/_customer/dashboard': {
      preLoaderRoute: typeof CustomerDashboardImport
      parentRoute: typeof CustomerImport
    }
    '/_agent/agent/dashboard': {
      preLoaderRoute: typeof AgentAgentDashboardImport
      parentRoute: typeof AgentImport
    }
    '/_customer/transactions/add': {
      preLoaderRoute: typeof CustomerTransactionsAddImport
      parentRoute: typeof CustomerImport
    }
    '/_agent/agent/accounts/add': {
      preLoaderRoute: typeof AgentAgentAccountsAddImport
      parentRoute: typeof AgentImport
    }
    '/_agent/agent/customers/add': {
      preLoaderRoute: typeof AgentAgentCustomersAddImport
      parentRoute: typeof AgentImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AgentRoute.addChildren([
    AgentAgentDashboardRoute,
    AgentAgentAccountsAddRoute,
    AgentAgentCustomersAddRoute,
  ]),
  CustomerRoute.addChildren([
    CustomerDashboardRoute,
    CustomerTransactionsAddRoute,
  ]),
])

/* prettier-ignore-end */
